<a href="https://colab.research.google.com/github/aswinrj401-del/AI-DEEP-VISION/blob/main/DAY2task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#1
ar = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#2
print(ar[:,0])

[1 4 7]


In [5]:
#3
print(ar[2,:])

[7 8 9]


In [6]:
#4
print(ar[1,1])

5


In [7]:
#5
print(ar[1,0])

4


In [8]:
#6
print(ar.diagonal())

[1 5 9]


In [33]:
#7
print(ar[::-1])


[[7 0 9]
 [0 5 0]
 [1 0 3]]


In [32]:
#8
ar[ar % 2==0]=0
print(ar)

[[1 0 3]
 [0 5 0]
 [7 0 9]]


In [11]:
#9
print(ar.shape)
print(ar.size)
print(ar.ndim)
print(ar.dtype)

(3, 3)
9
2
int64


In [12]:
#10
print(ar.sum())
print(ar.max())
print(ar.mean())
print(ar.min())

45
9
5.0
1


In [21]:
#11
arr = np.arange(1,25)
print("og")
print(arr,"\n")
print("reshaped")
print(arr.reshape(6,4),"\n")
print("reshaped2")
print(arr.reshape(2,3,4),"\n")

og
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 

reshaped
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 

reshaped2
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] 



In [29]:
#12
ran = np.random.randint(25,100,20)
print(ran)
print("mean")
print(ran.mean())
print("median")
print(np.median(ran))
print("standard deviation")
print(ran.std())

[96 87 28 97 34 39 63 90 96 32 99 76 63 32 80 70 32 31 60 66]
mean
63.55
median
64.5
standard deviation
25.49799011687


In [30]:
#13
print(ran[ran>50])


[96 87 97 63 90 96 99 76 63 80 70 60 66]


In [31]:
#14
ran[ran < 50] = 50
print(ran)

[96 87 50 97 50 50 63 90 96 50 99 76 63 50 80 70 50 50 60 66]


In [35]:
#15
ar = np.array(([1,2,3],[4,5,6],[7,8,9]))
ar1 = np.array(([10,11,12],[13,14,15],[16,17,18]))
sum_arr = ar + ar1
sub_arr = ar - ar1
mul_arr = ar * ar1

print(sum_arr)
print(sub_arr)
print(mul_arr)
print(ar.transpose())

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
